logging:
  level:
    org:
      springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: mono-tweet

  datasource:
    # url: jdbc:h2:mem:mono_tweet
    url: jdbc:mysql://localhost:3306/mono_tweet
    username: user
    password: user_password

  h2:
    console:
      enabled: true

  security:
    user:
      name: root
      password: password

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
